---
title: "Sampling test"
author: "Jason Flower"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(terra)
library(magrittr)

source("../functions/cluster_to_rast.R")
source("../functions/optimal_cluster_size_timing.R")
source("../functions/clustering_data.R")
```

```{r data setup include=FALSE}
bio_oracle_data <- list.files("../data/bio_oracle/", full.names = TRUE) |>
    terra::rast()

area_polygon <- mregions2::mrp_get("eez", cql_filter = "territory1 = 'Micronesia'") |>
  vect()
```

# Sample sizes test

More than 10000 rows will not be possible due to time and memory consumption: ~20000 cells with max number of clusters = 8 takes >2 mins and suck up more than 8GB of RAM

```{r}
set.seed(1234)

data_for_clustering_df <- clustering_data(area_polygon = area_polygon, num_cells = 1e5)

sample_sizes <- c(10^(1:4), 5000, 7500)

sample_size_results <- optimal_cluster_size_timing(sample_sizes = sample_sizes, max_num_clusters = 8, data_for_clustering_df = data_for_clustering_df)

knitr::kable(sample_size_results)
```

# Max number of clusters test

```{r}
data_for_clustering_df <- clustering_data(area_polygon = area_polygon, num_cells = 1e4)

max_num_clusters <- 4:8

max_clusters_results <- optimal_cluster_size_timing(sample_sizes = NULL, max_num_clusters = max_num_clusters, data_for_clustering_df = data_for_clustering_df)

knitr::kable(max_clusters_results)
```

# Multiple samples for consensus

```{r}
set.seed(1234)

data_for_clustering_df <- clustering_data(area_polygon = area_polygon, num_cells = 1e5)

sample_sizes <- rep(5000, 5)

results_consensus <- optimal_cluster_size_timing(sample_sizes = sample_sizes, max_num_clusters = 6, data_for_clustering_df = data_for_clustering_df)

knitr::kable(results_consensus)
```

Try with larger dataset

```{r}
set.seed(1234)

data_for_clustering_df <- clustering_data(area_polygon = area_polygon, num_cells = 1e7)

sample_sizes <- rep(5000, 5)

results_consensus <- optimal_cluster_size_timing(sample_sizes = sample_sizes, max_num_clusters = 6, data_for_clustering_df = data_for_clustering_df)

knitr::kable(results_consensus)
```

# Parallel

```{r}
set.seed(1234)

data_for_clustering_df <- clustering_data(area_polygon = area_polygon, num_cells = 1e7)

sample_size <- 5000

num_clustering_runs <- 5

max_num_clusters <- 6

num_cores <- 5
start_time <- Sys.time()

df_sample <- lapply(rep(5000,5), function(x) data_for_clustering_df[sample.int(nrow(data_for_clustering_df), x),])

best_no_clusts <- sapply(df_sample, function(x) NbClust::NbClust(data = x, method = "kmeans", max.nc = max_num_clusters,  index = "hartigan") %>% .[[2]] %>% .["Number_clusters"])

difftime(Sys.time(), start_time)

#parallel version

start_time <- Sys.time()

df_sample <- lapply(rep(5000,5), function(x) data_for_clustering_df[sample.int(nrow(data_for_clustering_df), x),])

if(Sys.info()["sysname"]=="Windows"){
  
  cluster <- parallel::makePSOCKcluster(num_cores)
  best_no_clusts <- parallel::parLapply(cluster, df_sample, function(x) NbClust::NbClust(data = x, method = "kmeans", max.nc = max_num_clusters,  index = "hartigan") %>% .[[2]] %>% .["Number_clusters"]) %>% 
    unlist()
  
}else{
  
best_no_clusts <- parallel::mclapply(df_sample, function(x) NbClust::NbClust(data = x, method = "kmeans", max.nc = max_num_clusters,  index = "hartigan") %>% .[[2]] %>% .["Number_clusters"], mc.cores = num_cores) %>% 
  unlist()
}

difftime(Sys.time(), start_time)

uniq_values <- unique(best_no_clusts)

uniq_values[which.max(tabulate(match(best_no_clusts, uniq_values)))]

```

```{r}
max_num_clusters <- 6

start_time <- Sys.time()
clust_result <- NbClust::NbClust(data = data_for_clustering_df, method = "kmeans", max.nc = max_num_clusters,  index = "hartigan")

print(difftime(Sys.time(), start_time))

print(clust_result$Best.nc)
```

```{r}
clust_ras <- cluster_to_rast(area_data, clust_result$Best.partition)

plot(clust_ras)
```

# Clustering with known number of clusters

```{r}
start_time <- Sys.time()
clust_result_kmeans <- kmeans(x = data_for_clustering_df, centers = clust_result$Best.nc[1], nstart = 10)

print("Run time = ", Sys.time()- start_time)

clust_ras_kmeans <- cluster_to_rast(area_data, clust_result_kmeans$cluster)



plot(clust_ras_kmeans)
```

